# File: netlify.toml

[build]
  # Pastikan command Anda persis seperti ini, dengan "npm install" untuk backend
  command = "npm run build && (cd ../backend && npm run migrate)"
  
  publish = "dist"
  base = "frontend"